language: node_js
node_js: -7
deploy:
  provider: heroku
  api_key:
    secure: G0aY+tNJadpoT0j8eRDhclIn1s4lzbCfxXrFoCHnu6xHqNTZdf4Vq+o7gtiYn/RQlTHsmtT75r0FjksjX4bkTz8oQ+kNK3ZwYftENsXDJe58XUQsdUOYgAzGmLY3rWsn6bSQl2IFKRkw2UyioqjRTgsYsGgoTbIzAD4rEQLy7GA7yAnk3+1CjBScQVu4aFFhTulOIDw8IqInJwVCI3ta052ioqV59LILK/6g5sjHMJ9E8dgyqgTZI2VjSPnJEErz64q5zLbHW8g/bn9zvSk9ojGZDbgFc41VOjLBXkLmXoZtYO2Xghe8pxIhEOYZgkgZQY+Z+uUjxTpQi73zbvnsswPsZnhbA0f0gi9QzsoIZTlmAd2fo7fxSbgx4CILNV9BBQgecu3JH8nKdGq9Ack6vreEQs3IhCZKNwXCy9oDrIEpSC6jccjjpdtGdQeYGCfXRaAvOetzS2yqsVxrOU9YkCL3v7YWy1lfC7HRcxzIru9IsPQyRsIih9edg95JSYBbDf+YXDW1Bi/3Arqf26vBzGuPRkBSk+Q/XxscEvvuL0sH+CqluSkT+Lo5cAaOMEZVrlBAAoC4RqZ3ZPsYewj1gEcVWQ0vn63nL02cVQLqOTGNkDOS5BG9w7ajJcKUK85YfYrcqmq+KcuABLUCfBxSirFpZo8UxB7UCmijSEGWeGw=
